In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
## Transpose
A = np.array([
    [1 ,8, -2],
    [5, -1, 3],
    [0, -3, 3]
])
print(A.T)
print(np.transpose(A))

[[ 1  5  0]
 [ 8 -1 -3]
 [-2  3  3]]
[[ 1  5  0]
 [ 8 -1 -3]
 [-2  3  3]]


In [18]:
## Dot Product
B = np.array([
    [1,5],
    [2,3]
])
C = np.array([
    [0,1],
    [2,0]
])
print(np.dot(B,C))
print(B@C)
print(np.matmul(B,C))

[[10  1]
 [ 6  2]]
[[10  1]
 [ 6  2]]
[[10  1]
 [ 6  2]]


In [4]:
## Inner dimensions must be equal (a,b)@(b,c)
D = np.array([
    [1,2],
    [3,4],
    [4,5]
    
])
E = np.array([
    [7,8],
    [1,2],
    [0,3]
])
F = np.array([
    [1,2],
    [3,4]
])
print(D@F)
print(E@F)
print(D@E)


[[ 7 10]
 [15 22]
 [19 28]]
[[31 46]
 [ 7 10]
 [ 9 12]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

$$ A = \begin{bmatrix} a \ b \\ c \ d \end{bmatrix} \\ det(A) \ or \ |A| =  a*d - \ b*c $$

In [6]:
## Determinant
B = np.array([
    [1,5],
    [2,3]
])
np.linalg.det(B)


-7.000000000000001

In [15]:
## Inverse 

G = np.array([
    [1,5],
    [3,9]
])
inv_G = np.linalg.inv(G)

G@inv_G

array([[1., 0.],
       [0., 1.]])