# Linear Algebra for CpE
## Laboratory 6 : Matrices

Now that you have a fundamental knowledge about vector representations, we'll try to look into greater dimensions.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.

# Discussion

In [36]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

Let's say for example you have $A$ and $B$ as system of equation.

$$
A = \left\{
    \begin{array}\\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$

We could see that $A$ is a system of 2 equations with 2 parameters. While $B$ is a system of 3 equations with 3 parameters. We can represent them as matrices as:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}
$$

So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in here in Python.

### Declaring Matrices

Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas $A$ is a matrix consisting of elements denoted by $a_{i,j}$. Denoted by $i$ is the number of rows in the matrix while $j$ stands for the number of columns.<br>
Do note that the $size$ of a matrix is $i\times j$.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using <b>shape</b>, <b>dimensions</b> and <b>size</b> attributes, we'll use them to analyze these matrices.

In [37]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [38]:
## Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [39]:
G = np.array([
    [1,1],
    [2,2]
])
describe_mat(G)

Matrix:
[[1 1]
 [2 2]]

Shape:	(2, 2)
Rank:	2



In [40]:
## Declaring a 3 x 2 matrix
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [41]:
H = np.array([1,2,3,4,5])
describe_mat(H)

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



## Categorizing Matrices

There are several ways of classifying matrices. Once could be according to their <b>shape</b> and another is according to their <b>element values</b>. We'll try to go through them.

### According to shape

#### Row and Column Matrices

Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be $1 \times j$ and column matrices would be $i \times 1$.

In [42]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    1, 3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 3 2]

Shape:	(3,)
Rank:	1

Matrix:
[[1 2 3]]

Shape:	(1, 3)
Rank:	2



In [43]:
## Declaring a Column Matrix

col_mat = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



#### Square Matrices

Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if $i = j$. We can tweak our matrix descriptor function to determine square matrices.

In [44]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [45]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False



### According to element values

#### Null Matrix

A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [46]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [47]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


#### Zero Matrix

A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [48]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


#### Ones Matrix

A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [49]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### Diagonal Matrix

A diagonal matrix is a square matrix that has values only at the diagonal of the matrix. 

In [50]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [51]:
d = np.diag([2,3,5,7])
np.diag(d).shape == d.shape[0] == d.shape[1]


False

#### Identity Matrix

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [52]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Upper Triangular Matrix

An upper triangular matrix is a matrix that has no values below the diagonal. 

In [54]:
np.array([
    [1,2,3],
    [0,3,1],
    [0,0,5]
])

array([[1, 2, 3],
       [0, 3, 1],
       [0, 0, 5]])

#### Lower Triangular Matrix

A lower triangular matrix is a matrix that has no values above the diagonal.

In [55]:
np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])

array([[1, 0, 0],
       [5, 3, 0],
       [7, 8, 5]])

## Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.

$$\theta = 5x + 3y - z$$

In [56]:
theta = np.array([
              [5,3,-1],
])
describe_mat(theta)

Matrix:
[[ 5  3 -1]]

Shape:	(1, 3)
Rank:	2
Is Square: False



2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

In [57]:
number2_mat = np.array([
             [1,2,1],
             [0,4,-1],
             [0,0,10]
])
describe_mat(number2_mat)

Matrix:
[[ 1  2  1]
 [ 0  4 -1]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2
Is Square: True



3. Given the matrix below, express it as a linear combination in a markdown.

In [58]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


$$G = 
\begin{bmatrix}1&7&8\\2&2&2\\4&6&7
\end{bmatrix}$$

$$G=\left\{\begin{array} 1g_1+7g_2+8g_3 \\2g_1+2g_2+2g_3\\4g_1+6g_2+7g_3
\end{array}\right.$$

4. Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations.

In [59]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

$$
H = \left\{\begin{array}
1x_1\\
2x_1+ 2y_2\\
4x_1+ 6y_2 +7z_3
\end{array}\right.
$$

$$\begin{equation*}
H = 
\begin{bmatrix}
1 & 0 & 0 \\
2 & 2 & 0 \\
4 & 6 & 7
\end{bmatrix}
\end{equation*}$$

# Matrix Algebra

### Addition

In [60]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [0,0],
    [1,1]
])
A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In [61]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[3, 4],
       [4, 5],
       [6, 3]])

### Subtraction

In [62]:
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [63]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

### Element-wise Multiplication

In [64]:
A*B
np.multiply(A,B)

array([[2, 4],
       [0, 0],
       [4, 1]])

In [65]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

In [66]:
alpha=10**-10
A/(alpha+B)

array([[5.e-01, 1.e+00],
       [2.e+10, 3.e+10],
       [4.e+00, 1.e+00]])

In [67]:
np.add(A,B)

array([[3, 4],
       [2, 3],
       [5, 2]])

## Activity

### Task 1

Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [68]:
def mat_desc(matrix):
    print("Shape of the matrix:", matrix.shape)
    print("Rank of the matrix:",matrix.ndim)
    print("Size of the matrix:",matrix.size)
    if matrix.size > 0: 
        if(matrix.shape[0] == matrix.shape[1]):
            print("The matrix \n",matrix,"\nis a square matrix")
        else:
            print("The matrix\n",matrix,"\nis non-square matrix")
        if np.array_equal(matrix,np.ones(matrix.shape)):
            print("The matrix \n",matrix,"\nis a ones matrix")
        elif np.array_equal(matrix,np.zeros(matrix.shape)):
            print("The matrix \n",matrix,"\nis a zero matrix")
        elif np.array_equal(matrix,np.eye(len(matrix))):
            print("The matrix \n",matrix,"\nis an identity matrix")
    else:
        print("The matrix\n",matrix,"\nis an empty matrix")

In [69]:
A = np.array([
    [1,1,1],
    [2,2,2],
    [3,3,3]
])
B = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
    
])
C = np.array([])
D = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]
])
E = np.array([
    [0,0,0],
    [0,0,0],
    [0,0,0]
])
F = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])
G = 5
listofmat = [A,B,C,D,E,F,G]
strlistofmat = ["A","B","C","D","E","F","G"]

In [70]:
for matrices,letters in zip(listofmat,strlistofmat):
    print("Matrix",letters)
    mat_desc(matrices)
    print("\n")

Matrix A
Shape of the matrix: (3, 3)
Rank of the matrix: 2
Size of the matrix: 9
The matrix 
 [[1 1 1]
 [2 2 2]
 [3 3 3]] 
is a square matrix


Matrix B
Shape of the matrix: (3, 4)
Rank of the matrix: 2
Size of the matrix: 12
The matrix
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 
is non-square matrix


Matrix C
Shape of the matrix: (0,)
Rank of the matrix: 1
Size of the matrix: 0
The matrix
 [] 
is an empty matrix


Matrix D
Shape of the matrix: (3, 3)
Rank of the matrix: 2
Size of the matrix: 9
The matrix 
 [[1 1 1]
 [1 1 1]
 [1 1 1]] 
is a square matrix
The matrix 
 [[1 1 1]
 [1 1 1]
 [1 1 1]] 
is a ones matrix


Matrix E
Shape of the matrix: (3, 3)
Rank of the matrix: 2
Size of the matrix: 9
The matrix 
 [[0 0 0]
 [0 0 0]
 [0 0 0]] 
is a square matrix
The matrix 
 [[0 0 0]
 [0 0 0]
 [0 0 0]] 
is a zero matrix


Matrix F
Shape of the matrix: (3, 3)
Rank of the matrix: 2
Size of the matrix: 9
The matrix 
 [[1 0 0]
 [0 1 0]
 [0 0 1]] 
is a square matrix
The matrix 
 [[1 0 0]
 [0 1 

AttributeError: 'int' object has no attribute 'shape'

### Task 2

Create a function named `mat_operations()` that takes in two matrices or scalars a input parameters it should:<br>
 1. Display the description of each matrix, if the parameter is a scalar it tells that it is a scalar rather than describing it as a matrix.
 2. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 3. Returns the sum of the matrices.
 4. Returns the differen of the matrices.
 5. Returns the element-wise multiplication of the matrices.
 6. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
def mat_operations(first_mat,second_mat):
    if type(first_mat) == type(int()) or type(first_mat) == type(float()) or first_mat.ndim == 1:
        print("The first parameter is a scalar")
        print("---------------------------------------------------------------------")
        
    else:
        print("Shape of the first matrix:", first_mat.shape)
        print("Rank of the first matrix:",first_mat.ndim )
        if first_mat.size > 0: 
            if(first_mat.shape[0] == first_mat.shape[1]):
                print("The first matrix \n",first_mat,"\nis a square matrix")
            else:
                print("The first matrix\n",first_mat,"\nis not a square matrix")
            if np.array_equal(first_mat,np.ones(first_mat.shape)):
                print("The first matrix \n",first_mat,"\nis a ones matrix")
            elif np.array_equal(first_mat,np.zeros(first_mat.shape)):
                print("The first matrix \n",first_mat,"\nis a zero matrix")
            elif np.array_equal(first_mat,np.eye(len(first_mat))):
                print("The first matrix \n",first_mat,"\nis an identity matrix")
            print("---------------------------------------------------------------------")
        else:
            print("The first matrix\n",first_mat,"\nis an empty matrix\n")
            print("---------------------------------------------------------------------")

    if type(second_mat) == type(int()) or type(second_mat) == type(float()) or second_mat.ndim == 1:
        print("The second parameter is a scalar")
        print("---------------------------------------------------------------------")
    else:
        print("Shape of the second matrix :", second_mat.shape)
        print("Rank of the second matrix :",second_mat.ndim)
        if second_mat.size > 0: 
            if(second_mat.shape[0] == second_mat.shape[1]):
                print("The second matrix \n",second_mat,"\nis a square matrix")
            else:
                print("The second matrix\n",second_mat,"\nis not a square matrix")
            if np.array_equal(second_mat,np.ones(second_mat.shape)):
                print("The second matrix \n",second_mat,"\nis a ones matrix")
            elif np.array_equal(second_mat,np.zeros(second_mat.shape)):
                print("The second matrix \n",second_mat,"\nis a zero matrix")
            elif np.array_equal(second_mat,np.eye(len(second_mat))):
                print("The second matrix \n",second_mat,"\nis an identity matrix")
            print("---------------------------------------------------------------------")
        else:
            print("The second matrix\n",second_mat,"\nis an empty matrix\n")
            print("---------------------------------------------------------------------")
        
    try:
        sumofmat = print("Sum of the two matrices:\n", np.sum(np.add(first_mat,second_mat)))
    except:
        print("Invalid to perform sum operation ")
    try:
        diffofmat = print("Difference of the two matrices:\n", np.diff(np.subtract(first_mat,second_mat)))
    except:
        print("Invalid to perform difference operation ")
    try:
        prodofmat = print("Product of the two matrices:\n", np.multiply(first_mat,second_mat))
    except:
        print("Invalid to perform multiply operation ")
    try:
        quotofmat = print("Quotient of the two matrices\n", np.divide(first_mat,second_mat))
    except:
        print("Invalid to perform divide operation ")
        
        
        

In [ ]:
A = np.array([
    [1,1,1],
    [2,2,2],
    [3,3,3]
])
B = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [1,3,5,7]
])

C = np.array([
    [5,25,125],
    [100,121,144],
    [10,11,12]
])
D = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]
])
E = np.array([
    [1,2,4],
    [1,3,9],
    [1,4,16]    
])
F = np.array([
    [5,10,15],
    [3,6,9],
    [1,3,5]
])
G = 5


In [ ]:
print("Matrix A and B")
mat_operations(A,B)
print("Matrix C and D")
mat_operations(C,D)
print("Matrix G and E")
mat_operations(G,E)

$$ A = \begin{cases} 2x+3y+5z\\5x+7y\\8y+9z \end{cases} \\ A = \begin{bmatrix} 2 \ 3 \ 5\\ 5 \ 7 \ 0 \\ 0 \ 8 \ 9 \end{bmatrix}$$

## Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "how can matrix operations solve problems in agriculture?".