In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [9]:
## According to shape
# Row Matrix
A = np.array([
    5,3
])
print(A.shape)
print(A.ndim)
B = np.array([
    [5,3]
])
print(B.shape)
print(B.ndim)

# Column Matrix
C = np.array([
    [5],
    [4]
])
print(C.shape)
print(C.ndim)


(2,)
1
(1, 2)
2
(2, 1)
2


In [22]:
## Square Matrix

D = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
## Null Matrix
E = np.array([])
E


array([], dtype=float64)

In [25]:
## Zero Matrix
print(np.array([
    [0,0],
    [0,0]
]))
print(np.zeros((2,2)))


[[0 0]
 [0 0]]
[[0. 0.]
 [0. 0.]]


In [26]:
## Ones Matrix
print(np.array([
    [1,1],
    [1,1]
]))
print(np.ones((2,2)))


array([[1., 1.],
       [1., 1.]])

In [30]:
## Diagonal Matrix
print(np.array([
    [2,0,0],
    [0,3,0],
    [0,0,4]
]))
print(np.diag([2,3,5]))



[[2 0 0]
 [0 3 0]
 [0 0 4]]
[[2 0 0]
 [0 3 0]
 [0 0 5]]


In [31]:
## Identity Matrix
print(np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
]))
print(np.eye(3))



[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
## Upper Triangular Matrix
np.array([
    [2,3,5],
    [0,5,7],
    [0,0,9]
])



array([[2, 3, 5],
       [0, 5, 7],
       [0, 0, 9]])

In [33]:
## Lower Triangular Matrix
np.array([
    [1,0,0],
    [2,3,0],
    [4,5,6]
])

array([[1, 0, 0],
       [2, 3, 0],
       [4, 5, 6]])